meta_product_name: "Cardable"
meta_title: "Cardable - vouchers solution"
meta_description: "Cardable is a free app built for restaurant owner. It permits to improve the restaurant's turnover thanks to gift vouchers. "
meta_image: "logo-cardable.png"
